stages:
  - build
  - test

variables:
  SOLUTION_FILE: "WebAPI.sln"
  API_PROJECT: "API/API.csproj"
  TEST_PROJECT_DIR: "Tests/Tests.csproj"
  PUBLISH_OUTPUT_DIR: "publish-output"
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://*:5000"

before_script:
  - export PATH="$PATH:$HOME/.dotnet/tools"

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet restore $SOLUTION_FILE
    - dotnet build $SOLUTION_FILE --configuration Release --no-restore
    - dotnet publish $API_PROJECT --configuration Release --no-build --output $PUBLISH_OUTPUT_DIR
  artifacts:
    paths:
      - Tests/bin/Release/
      - $PUBLISH_OUTPUT_DIR/
    expire_in: 1h

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet tool install -g trx2junit
    - export PATH="$PATH:$HOME/.dotnet/tools"

    - dotnet test $TEST_PROJECT --configuration Release --no-build --logger "trx;LogFileName=testresults.trx"

    - trx2junit Tests/**/testresults.trx
  artifacts:
    reports:
      junit: "Tests/**/testresults.xml"
    when: always
    paths:
      - Tests/**/testresults.trx
      - Tests/**/testresults.xml
    expire_in: 1h