image: mcr.microsoft.com/dotnet/sdk:8.0-preview

services:
  - name: postgres:17
    alias: postgres

variables:
  POSTGRES_DB: mydb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin
  CONNECTION_STRING: "Host=postgres;Database=mydb;Username=postgres;Password=admin"
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"

stages:
  - build
  - test
  - deploy

before_script:
  - dotnet tool install --global dotnet-ef
  - export PATH="$PATH:/root/.dotnet/tools"
  - dotnet --info
  - dotnet ef --version
  - dotnet restore

build_job:
  stage: build
  tags: [docker]
  script:
    - dotnet build --configuration Release --no-restore --no-dependencies

test_job:
  stage: test
  tags: [docker]
  script:
    - dotnet test --configuration Release --no-build --verbosity normal
  timeout: 5 minutes

deploy_job:
  stage: deploy
  tags: [docker]
  script:
    - apt update && apt install -y postgresql-client
    - timeout 30s bash -c 'until pg_isready -h postgres -U postgres; do sleep 1; done'
    - dotnet ef database update --connection "$CONNECTION_STRING" --project Data --startup-project WebApi
  when: manual