stages:
  - build
  - test
  - deploy

variables:
  SOLUTION_FILE: "WebAPI.sln"
  API_PROJECT: "API/API.csproj"
  TEST_PROJECT: "Tests/Tests.csproj"
  PUBLISH_OUTPUT_DIR: "publish-output"
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://*:5245"

  POSTGRES_DB: "practice_migration_test_bd"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "admin"
  CONNECTION_STRING: "Host=localhost;Port=5432;Database=practice_migration_test_bd;Username=postgres;Password=admin"

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  services:
    - name: postgres:latest
      alias: postgres
      variables:
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  script:
    - export PATH="$PATH:$HOME/.dotnet/tools"
    - dotnet restore $SOLUTION_FILE
    - dotnet build $SOLUTION_FILE --configuration Release --no-restore
    - dotnet publish $API_PROJECT --configuration Release --no-build --output $PUBLISH_OUTPUT_DIR

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  dependencies:
    - build
  script:
    - dotnet tool install -g trx2junit
    - export PATH="$PATH:$HOME/.dotnet/tools"
    - dotnet vstest $TEST_PROJECT --configuration Release --no-build

deploy:
  stage: deploy
  image: mcr.microsoft.com/dotnet/aspnet:8.0
  services:
    - name: postgres:latest
      alias: postgres
      variables:
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  script:
    - dotnet tool install --global dotnet-ef
    - export PATH="$PATH:$HOME/.dotnet/tools"
    - dotnet ef database update --project $API_PROJECT --connection "$CONNECTION_STRING" || echo "Migrations not configured"

    - cd $PUBLISH_OUTPUT_DIR
    - dotnet test_API.dll --urls=$ASPNETCORE_URLS &
    - sleep 15

  environment:
    name: production
    url: http://192.168.56.1:5245/swagger
  only:
    - main
